### ISSUE TITLE
Backwards compatibility break due to acorn dependency

### ISSUE THREAD

**Issue by senko** [ForbesLindesay/with#7]
The latest acorn release (1.0.1) breaks compatibility with the previous 0.x releases: https://github.com/marijnh/acorn/issues/235

The current version of this package (4.0.2) depends on a version compatible with 1.0.1, thus breaking compatibility without increasing its own major version.

In practice, this breaks our jade templates that contain variable names clashing with reserved keywords.

The only way I can think of fixing this is releasing 4.0.3 depending back on 0.11.x, and 5.0.x depending on 1.0.1, but hopefully there's a less intrusive way of doing so.

**Comment by jackspaniel** [comment]
FYI - I posted this issue in the acorn repo: https://github.com/marijnh/acorn/issues/235

**Comment by hawkerboy7** [comment]
Got the same problem! +1

**Comment by ForbesLindesay** [comment]
Sorry about this.  acorn broke backwards compatibility in many ways.  I dealt with (most) intentional changes, but they also accidentally broke browserify support and created a bug where `yield` is not supported in ES6 mode.

The browserify bug @hawkerboy7 is experiencing is being tracked by https://github.com/marijnh/acorn/issues/232 and https://github.com/marijnh/acorn/pull/237.  You should seriously consider using jade server-side to pre-compile your jade files using `jade --client foo.jade` then only including the jade runtime.  This will be waaaay more performant and have much better browser support.

**Comment by hawkerboy7** [comment]
I use [id-builder](https://github.com/Industrial/id-builder) which uses browserify and other modules to do what you describe if I am not mistaken. Jade files are turned into .js files and those are then turned into a bundle by browserify. However the user now still needs `window.jade = require('jade').runtime` on the client side to make the .jade -> .js templates work.

**Comment by ForbesLindesay** [comment]
Instead, you can add `var jade = require ('jade/lib/runtime')` for a bundle that's thousands of times smaller :)

**Comment by hawkerboy7** [comment]
Great thank you! =D
